invitati = [["Familia", "Numar Persoane", "numar Masa"],
            ["Trantu Stelian ","","25"],
            ["Nicolae Damu ","","25"],
            ["Nicolae Nicoale ","","25"],
            ["Stere Stere ","","25"],
            ["Nicolae Mihai ","","25"],
            ["Stere Stere","","25"],
            ["Negreanu Dani ","","17"],
            ["Negreanu Cristi ","","17"],
            ["Negreanu Adrian ","","17"],
            ["Negreanu Bogdan ","","17"],
            ["Negreanu Laurentiu Lalu ","","17"],
            ["Negreanu Gigi Lala ","","16"],
            ["Roibu Nicu ","","16"],
            ["Negreanu Marcel - Geanina ","","16"],
            ["Negreanu Marcel - Aurora ","","16"],
            ["Pucerea Dimciu ","","16"],
            ["Negreanu Gigi- dana ","","19"],
            ["Seghedi Gelu ","","19"],
            ["Halep Fane ","","19"],
            ["Moinea Nelu ","","19"],
            ["Negreanu Mitus ","","19"],
            ["Moroianu Vasilica ","","26"],
            ["Dudu Ion ","","26"],
            ["Plaiesu Mihaela ","","26"],
            ["Apolozan Costel ","","26"],
            ["Leut Marcela ","","26"],
			["Alexandru Laurentiu ","","26"],
            ["Leu Catalin ","","24"],
            ["Buliga Costel ","","24"],
            ["Filimon Ionut ","","24"],
            ["Pamfil Marcel ","","24"],
            ["Oprea Marin ","","24"],
            ["Rusu Costel ","","20"],
            ["Caplat Simi ","","20"],
            ["Pomana Bogdan ","","20"],
            ["Dobrogeanu Silica ","","20"],
            ["Tomosoiu Titi ","","20"],
            ["Dumitru Enache ","","23"],
            ["Pasata Adam ","","23"],
            ["Uda Gica ","","23"],
            ["Enache Mihai ","","23"],
            ["Chiriac Nicoleta ","","23"],
            ["Vitu George ","","22"],
            ["Vizuroiu Florin ","","22"],
            ["Camciuc Marius ","","22"],
            ["Craciun Niculina ","","22"],
            ["Alexandru Mihai - Catalina ","","22"],
            ["Olaru Vali ","","21"],
            ["Mircea Victor ","","21"],
            ["Rusu Nicu ","","21"],
            ["Corchi Stefan ","","21"],
            ["Mircea Gigi","","21"],
            ["Rusu Nelu ","","13"],
            ["Rusu Marin ","","13"],
            ["Vraciu Bogdan ","","13"],
            ["Popa Luminita ","","13"],
            ["Andrei Adrian ","","13"],
            ["Copil Gina ","","13"],
            ["Iorganda Gigi","","13"],
            ["Tabarcea Dan ","","14"],
            ["Tabarcea Mihai ","","14"],
            ["Tabarcea Costica ","","14"],
			["Diaconu Florica ","","14"],
            ["Diaconu Sandu ","","15"],
			["Rusu Sandu ","","15"],
            ["Memeleanu Adela ","","15"],
            ["Gales Radu ","","15"],

            ["Tabarcea Floarea ","","15"],
            ["Jurcaneanu Gheorghe Cel Mare","","15"],
            ["Barbu Adina ", "", "8"],
            ["Micu Dumitru","","8"],
            ["Auram Stefan","","8"],
            ["Craciun Mioara","","8"],
            ["Doleanu Doru","","8"],
            ["Burta Ghearghe","","1"],
            ["Timofte Miluta","","1"],
            ["Timofte Marinela","","1"],
            ["Pacurici Adi","","1"],
            ["Timofte Tania","","1"],
            ["Burta Lenuta","","1"],
            ["Neacsu Ionel","","2"],
            ["Marr Sever","","2"],
            ["Gazdaru Relu","","2"],
            ["Artimov Vasile","","2"],
            ["Pelivan Ion","","2"],
            ["Burta Dan","","3"],
            ["Dumitrache Ion","","3"],
            ["Burta Nicu","","3"],
            ["Burta George","","3"],
            ["Burta Catalin","","3"],
            ["Burta Vasile","","3"],
            ["Dima Florin","","4"],
            ["Dima Gabi","","4"],
            ["Vasiliev Liudmila","","4"],
            ["Jelescu Cristian","","4"],
             ["Buzoianu Marian","","4"],
            ["Alexe Adrian ","","5"],
            ["Bucur Sorin","","5"],
            ["Alexe Vasilica","","5"],
            ["Baciu Costel","","5"],
            ["Peiciu Vasile","","5"],
            ["Carlan Gabriel","","6"],
            ["Balanuta Sinica","","6"],
            ["Stoiu Vasile","","6"],
            ["Pacaleanu Marius","","6"],
            ["Buta Velic","","6"],
            ["Agache Marcel","","7"],
            ["Dache Catalin","","7"],
            ["Ene Cristian","","7"],
            ["Haralambe Hari","","7"],
            ["Ovidiu ", "","7"],
            ["Gherasim Dan", "","7"],
            ["Potoleanu Vasile","","18"],
            ["Maria Mama Nasa","","18"],
            ["Nedelcu Stefan","","18"],
            ["Delia Nedelcu ","","18"],
            ["Ciudesnic George ","","18"],
            ["Jecu Emil ","","18"],
            ["Luminare Aura","","9"],
            ["Achimov Daniel  ","","9"],
            ["Papaiani Luminita","","9"],
            ["Craciun Vasile","","9"],
            ["Constandache Marina","","9"],
            ["Finii Marina", "","9"],
            ["Ciobotaru Texas","","12"],
            ["Ciobotaru Serif","","12"],
            ["Ciudesnic Marian","","12"],
            ["Odagiu Adrian","","12"],
            ["Timofte Nicu","","12"],
            ["Mitriu Ciprian","","12"],
            ["Morosan Stefan","","10"],
            ["Lungu Florentina","","10"],
            ["Stancu Andreea","","10"],
            ["Pascu Irina","","10"],
            ["Moraru Tudor","","10"],
            ["Rasid Mensur Selhan","","10"],
            ["Jurcaneanu Ionut Adrian","","11"],
            ["Tabarcea Alexandru","","11"],
            ["Ciolmec Ana","","11"],
            ["Leut Marius","","11"],
            ["Despina Alexandra","","11"],
            ["Burta Bianca","","11"],
            ["Ionita Albert","","11"],
            ["Bumbac Alexandra","","11"],
            ["Dragomir Georgiana"," ", "11"]
            ] 

sorted_invitati = sorted(invitati, key = lambda x:x[0])

with open('output_rows_test.txt', 'w') as file:
    # Iterate over each row in the matrix
    for row in sorted_invitati:
        # Join the elements in the row into a single string, separated by spaces
        row_line = ' '.join(row)
        
        # Write the row to the file
        file.write(row_line + '\n')
print("Matrix columns written to output_final.txt") 

